# Generated by Django 5.2.10 on 2026-03-21 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='direction',
            field=models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tradeaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tradecost',
            name='incurred_at',
            field=models.DateField(blank=True, help_text='Date the cost was incurred (useful for daily swap charges)', null=True),
        ),
    ]
