# Generated by Django 5.2.10 on 2026-03-21 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('trades', '0002_trade_direction_tradeaccount_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignalstats',
            name='average_pips',
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='trade_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_snapshots', to='trades.tradeaccount'),
        ),
        migrations.AddField(
            model_name='signalperformance',
            name='tp_level_hit',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Which TP level was hit (1, 2, 3, ...)', null=True),
        ),
        migrations.AddField(
            model_name='usersignalstats',
            name='average_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usersignalstats',
            name='average_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usersignalstats',
            name='calculated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usersignalstats',
            name='losing_signals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersignalstats',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersignalstats',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersignalstats',
            name='total_pips',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='usersignalstats',
            name='total_profit_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='usersignalstats',
            name='trade_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_stats', to='trades.tradeaccount'),
        ),
        migrations.AlterField(
            model_name='usersignalstats',
            name='average_rr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
