# Generated by Django 5.2.10 on 2026-03-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('analyst', 'Analista'), ('trader', 'Trader')], default='trader', max_length=20),
        ),
    ]
