# Generated by Django 5.2.10 on 2026-01-25 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('discord', 'Discord'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_private', models.BooleanField(default=True)),
                ('timezone', models.CharField(default='UTC', help_text='Timezone of the signal source', max_length=50)),
                ('language', models.CharField(default='es', max_length=10)),
                ('signal_style', models.CharField(blank=True, choices=[('scalping', 'Scalping'), ('day', 'Day Trading'), ('swing', 'Swing Trading')], max_length=20, null=True)),
                ('risk_profile', models.CharField(blank=True, choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signal Source',
                'verbose_name_plural': 'Signal Sources',
            },
        ),
        migrations.CreateModel(
            name='SignalProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('alias', models.CharField(blank=True, help_text='Nickname or username', max_length=150)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('experience_level', models.CharField(blank=True, help_text='Beginner / Pro / Unknown', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('signal_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='signals.signalsource')),
            ],
            options={
                'verbose_name': 'Signal Provider',
                'verbose_name_plural': 'Signal Providers',
                'unique_together': {('name', 'signal_source')},
            },
        ),
        migrations.CreateModel(
            name='TradingSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=12)),
                ('stop_loss', models.DecimalField(decimal_places=5, max_digits=12)),
                ('execution_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop')], default='market', max_length=10)),
                ('confidence_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True)),
                ('session', models.CharField(blank=True, choices=[('asia', 'Asia'), ('london', 'London'), ('new_york', 'New York')], max_length=20, null=True)),
                ('timeframe', models.CharField(blank=True, help_text='M1, M5, M15, H1, etc.', max_length=10)),
                ('signal_time', models.DateTimeField(help_text='Original signal time (when it was sent)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('hit_tp', 'Hit Take Profit'), ('hit_sl', 'Hit Stop Loss')], default='active', max_length=20)),
                ('raw_message', models.TextField(blank=True, help_text='Original signal message')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('signal_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='signals.signalprovider')),
                ('signal_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='signals.signalsource')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trading Signal',
                'verbose_name_plural': 'Trading Signals',
            },
        ),
        migrations.CreateModel(
            name='SignalContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('market_condition', models.CharField(blank=True, choices=[('trending', 'Trending'), ('ranging', 'Ranging')], max_length=20, null=True)),
                ('volatility_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, null=True)),
                ('news_related', models.BooleanField(default=False)),
                ('commentary', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('trading_signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='signals.tradingsignal')),
            ],
            options={
                'verbose_name': 'Signal Context',
                'verbose_name_plural': 'Signal Contexts',
            },
        ),
        migrations.CreateModel(
            name='SignalTakeProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=5, max_digits=12)),
                ('level', models.PositiveSmallIntegerField(help_text='TP level (1, 2, 3, etc.)')),
                ('percentage_close', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of position to close', max_digits=5, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('trading_signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_profits', to='signals.tradingsignal')),
            ],
            options={
                'verbose_name': 'Signal Take Profit',
                'verbose_name_plural': 'Signal Take Profits',
                'ordering': ['level'],
                'unique_together': {('trading_signal', 'level')},
            },
        ),
    ]
