# Generated by Django 5.2.10 on 2026-03-20 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawTelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_message_id', models.BigIntegerField(help_text='Telegram internal message ID')),
                ('channel_id', models.BigIntegerField(help_text='Telegram chat/channel ID')),
                ('channel_title', models.CharField(blank=True, help_text='Display name of the chat or channel', max_length=255)),
                ('channel_username', models.CharField(blank=True, help_text='@username of the channel (if public)', max_length=100)),
                ('sender_id', models.BigIntegerField(blank=True, help_text='Telegram ID of the sender (null for anonymous channels)', null=True)),
                ('sender_name', models.CharField(blank=True, help_text='Display name of the sender', max_length=255)),
                ('raw_text', models.TextField(help_text='Full original message text')),
                ('message_date', models.DateTimeField(help_text='Timestamp when Telegram sent the message')),
                ('chat_type', models.CharField(blank=True, help_text='channel / group / private', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Raw Telegram Message',
                'verbose_name_plural': 'Raw Telegram Messages',
                'ordering': ['-message_date'],
                'unique_together': {('channel_id', 'telegram_message_id')},
            },
        ),
    ]
