# Generated by Django 5.2.10 on 2026-03-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_rawtelegrammessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawtelegrammessage',
            name='telegram_account_id',
            field=models.IntegerField(blank=True, help_text='ID de la TelegramAccount que recibio este mensaje', null=True),
        ),
    ]
