# Generated by Django 5.2.10 on 2026-03-20 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Nombre descriptivo de la cuenta (ej: "Cuenta Principal")', max_length=150)),
                ('api_id', models.IntegerField(help_text='API ID obtenido desde my.telegram.org')),
                ('api_hash', models.CharField(help_text='API Hash obtenido desde my.telegram.org', max_length=64)),
                ('phone_number', models.CharField(help_text='Numero de telefono con codigo de pais (ej: +59178535699)', max_length=20, unique=True)),
                ('session_name', models.CharField(editable=False, help_text='Nombre del archivo de sesion (auto-generado)', max_length=100, unique=True)),
                ('pid', models.IntegerField(blank=True, editable=False, help_text='PID del proceso listener activo', null=True)),
                ('phone_code_hash', models.CharField(blank=True, editable=False, help_text='Hash temporal del codigo enviado por Telegram', max_length=128)),
                ('awaiting_2fa', models.BooleanField(default=False, editable=False, help_text='Indica si la autenticacion esta esperando la contrasena 2FA')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Account',
                'verbose_name_plural': 'Telegram Accounts',
            },
        ),
    ]
